version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  nextjs:
    build: .
    container_name: next_app
    restart: always
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    # optional: for hot reload in dev
    # volumes:
      # - .:/app

volumes:
  mysql_data:
